### ISSUE TITLE
wrong argument type nil (expected Regexp) during absolutize_url

### ISSUE THREAD

**Issue by dallas** [purify/mail_style#13]
get this error

```
TypeError in Admin/email previewsController#show

wrong argument type nil (expected Regexp)
RAILS_ROOT: /Users/dallas/Sites/lead_generation

Application Trace | Framework Trace | Full Trace
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/mail_style-0.1.6/lib/mail_style/inline_styles.rb:162:in `gsub!'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/mail_style-0.1.6/lib/mail_style/inline_styles.rb:162:in `absolutize_url'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/mail_style-0.1.6/lib/mail_style/inline_styles.rb:162:in `each'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/mail_style-0.1.6/lib/mail_style/inline_styles.rb:162:in `absolutize_url'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/mail_style-0.1.6/lib/mail_style/inline_styles.rb:94:in `absolutize_image_sources'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/nokogiri-1.4.4/lib/nokogiri/xml/node_set.rb:239:in `each'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/nokogiri-1.4.4/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/nokogiri-1.4.4/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/mail_style-0.1.6/lib/mail_style/inline_styles.rb:92:in `absolutize_image_sources'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/mail_style-0.1.6/lib/mail_style/inline_styles.rb:48:in `parse_html'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/mail_style-0.1.6/lib/mail_style/inline_styles.rb:28:in `write_inline_styles'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/mail_style-0.1.6/lib/mail_style/inline_styles.rb:27:in `each'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/mail_style-0.1.6/lib/mail_style/inline_styles.rb:27:in `write_inline_styles'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/mail_style-0.1.6/lib/mail_style/inline_styles.rb:11:in `create_mail'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/actionmailer-2.3.11/lib/action_mailer/base.rb:542:in `create!'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/actionmailer-2.3.11/lib/action_mailer/base.rb:485:in `initialize'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/actionmailer-2.3.11/lib/action_mailer/base.rb:427:in `new'
/Users/dallas/.rvm/gems/ree-1.8.7-2010.02@leadgen/gems/actionmailer-2.3.11/lib/action_mailer/base.rb:427:in `method_missing'
```

and I'm guessing it is because I do not have `ActionMailer::Base.default_url_options[:host]` set at all… is this a requirement? The README makes it sound like this setting is optional and will only get used if it is set.

**Comment by dallas** [comment]
I have a branch which resolves this issue: https://github.com/qualitysmith/mail_style/commits/fix-default_url_options-bug

**Comment by anicholson** [comment]
This issue just bit me this morning - would be great if @dallas' fix could get pulled…
